# NumPy (Numerical Python) is a library for numerical computing in Python

#### Numerical computing allows us to perform complex calculations efficiently.

 Basic Arithmetic
 
 Matrix Operations
 
 Solving Linear Equations 
 
 Finding Eigenvalues and Eigenvectors
 
 Numerical Integration (Approximating Areas Under a Curve)
 
 Solving Differential Equations 

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5])  # 1D array
print(arr)

[1 2 3 4 5]


In [4]:
arr2D = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array
print(arr2D)

[[1 2 3]
 [4 5 6]]


In [6]:
print(arr2D.ndim)  # Number of dimensions
print(arr2D.shape)  # Shape of the array
print(arr2D.size)   # Total number of elements
print(arr2D.dtype)  # Data type of elements

2
(2, 3)
6
int32


In [12]:
zeros = np.zeros((3, 3))  # 3x3 matrix of zeros
ones = np.ones((2, 4))  # 2x4 matrix of ones
eye = np.eye(4)  # Identity matrix
rand = np.random.rand(3, 3)  # 3x3 random numbers (0 to 1)


print(zeros)
print(ones)
print(eye)
print(rand)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.51816077 0.17102523 0.93541299]
 [0.04351182 0.00975803 0.95446687]
 [0.54666791 0.79801689 0.16711035]]


In [9]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])  # First element
print(arr[-1])  # Last element
print(arr[1:4])  # Elements from index 1 to 3

10
50
[20 30 40]


In [10]:
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr2D[1, 2])  # Element at row 1, col 2
print(arr2D[:, 1])  # All rows, column 1
print(arr2D[0:2, 1:3])  # Sub-matrix

6
[2 5 8]
[[2 3]
 [5 6]]


## Array Operations

##### Element-wise Operations

In [14]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 + arr2)  # [5 7 9]
print(arr1 * arr2)  # [4 10 18]
print(arr1 ** 2)  # [1 4 9]

[5 7 9]
[ 4 10 18]
[1 4 9]


# Mathematical Functions

In [15]:
arr = np.array([1, 2, 3, 4])
print(np.sin(arr))
print(np.log(arr))
print(np.sqrt(arr))
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[0.         0.69314718 1.09861229 1.38629436]
[1.         1.41421356 1.73205081 2.        ]
10
2.5
4


# Broadcasting

In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr + 10)  # Adds 10 to all elements

[[11 12 13]
 [14 15 16]]


# Reshaping and Flattening

In [18]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
reshaped = arr.reshape((3, 2))  # Change shape
flattened = arr.flatten()  # Convert to 1D

print(arr)
print(reshaped)
print(flattened)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


# 8. Stacking and Splitting
### Stacking (Combining Arrays)




In [19]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(np.vstack((arr1, arr2)))  # Vertical stack

print(np.hstack((arr1, arr2)))  # Horizontal stack

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


# Splitting (Dividing Arrays)

In [20]:
arr = np.array([1, 2, 3, 4, 5, 6])

split_arr = np.split(arr, 3)  # Split into 3 equal parts

print(split_arr)

[array([1, 2]), array([3, 4]), array([5, 6])]


#  <span style="color: red"> Advanced NumPy Concepts </span>

###  <span style="color: blue"> Boolean Indexing </span>

In [22]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[arr > 25])  # Filters elements greater than 25

[30 40 50]


###  <span style="color: blue"> Fancy Indexing </span>

In [23]:
arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4]  # Selecting specific indices
print(arr[idx])

[10 30 50]


###  <span style="color: blue"> Sorting </span>

In [24]:
arr = np.array([3, 1, 4, 1, 5, 9])
print(np.sort(arr))  # Sorts in ascending order

[1 1 3 4 5 9]


###  <span style="color: blue"> Unique Elements </span>

In [25]:
arr = np.array([1, 2, 2, 3, 4, 4, 4, 5])
print(np.unique(arr))  # Removes duplicates

[1 2 3 4 5]


###  <span style="color: blue"> Random Sampling </span>

In [28]:
rand_ints = np.random.randint(1, 100, 5)  # 5 random numbers between 1-100
rand_normal = np.random.randn(3, 3)   # 3x3 matrix with normal distribution

print(rand_ints)
print(rand_normal)

[86  8 11 63 47]
[[-0.04706179 -0.15171253  1.11393977]
 [ 3.13306086  1.26730732 -0.78711455]
 [ 0.17494458  0.50189219  0.56790231]]


###  <span style="color: blue"> Linear Algebra with NumPy </span> 

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A, B))  # Matrix multiplication
print(np.linalg.det(A))  # Determinant of A
print(np.linalg.inv(A))  # Inverse of A
print(np.linalg.eig(A))  

In [ ]:
folder_path = "D:/"  # Change this to your desired path
file_name = "array.npy"
full_path = os.path.join(folder_path, file_name)

In [58]:
import numpy as np
import os

# Define the folder and filename
folder_path = "D:/MyData"  # Change this to your desired path
file_name = "array.npy"
full_path = os.path.join(folder_path, file_name)  # Combine folder and filename

# Create the folder if it doesn't exist
os.makedirs(folder_path, exist_ok=True)

# Create and save an array
arr = np.random.rand(3, 3)
np.save(full_path,arr)

print(f"File saved successfully at: {full_path}")

loaded_arr = np.load(full_path)  # Load array

print(loaded_arr)

File saved successfully at: D:/MyData\array.npy
[[0.89726381 0.13691525 0.53447211]
 [0.30105887 0.61455166 0.55431711]
 [0.73464279 0.90806596 0.57874235]]


# Load Multiple Arrays (.npz file)

In [62]:
np.savez("D:/MyData/data.npz", array1=np.arange(10), array2=np.random.rand(5,5))

# Load multiple arrays from a .npz file
loaded_data = np.load("D:/MyData/data.npz")

print("Array names in the file:", loaded_data.files)

# Access arrays dynamically
for name in loaded_data.files:
    print(f"Array '{name}':")

# Access individual arrays
array1 = loaded_data["array1"]
array2 = loaded_data["array2"]

print("Array 1:", array1)
print("Array 2:", array2)

Array names in the file: ['array1', 'array2']
Array 'array1':
Array 'array2':


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

# Save & Load NumPy Arrays Dynamically

In [63]:
import numpy as np
import os

# Step 1: Define the folder and filename
folder_path = "D:/MyData"  # Change this to your desired location
file_name = "data.npz"
full_path = os.path.join(folder_path, file_name)

# Step 2: Create the folder if it doesn't exist
os.makedirs(folder_path, exist_ok=True)

# Step 3: Create multiple arrays
array1 = np.arange(10)  # Array of numbers from 0 to 9
array2 = np.random.rand(5, 5)  # 5x5 random matrix
array3 = np.linspace(1, 50, 10)  # 10 evenly spaced numbers from 1 to 50

# Step 4: Save multiple arrays dynamically
np.savez(full_path, array1=array1, array2=array2, array3=array3)

print(f"✅ Arrays saved successfully at: {full_path}")

# ------------------------------------------
# Step 5: Load the .npz file dynamically
loaded_data = np.load(full_path)

# Step 6: Print all stored array names
print("📂 Arrays stored in the file:", loaded_data.files)

# Step 7: Store all arrays dynamically in a dictionary
arrays_dict = {name: loaded_data[name] for name in loaded_data.files}

# Step 8: Access arrays dynamically without hardcoding
for name, array in arrays_dict.items():
    print(f"\n🔹 Array Name: '{name}'")
    print(array)

# Step 9: Optionally, create global variables dynamically (use with caution)
for name in loaded_data.files:
    globals()[name] = loaded_data[name]  #  Automatically create variables using globals() so arrays can be accessed without dictionary lookup.

# Now you can access arrays without hardcoding names
print("\n🎯 Accessing arrays using dynamic variables:")
print("array1:", array1)  # Access dynamically created variable
print("array2:", array2)
print("array3:", array3)

✅ Arrays saved successfully at: D:/MyData\data.npz
📂 Arrays stored in the file: ['array1', 'array2', 'array3']

🔹 Array Name: 'array1'
[0 1 2 3 4 5 6 7 8 9]

🔹 Array Name: 'array2'
[[0.18251434 0.84915638 0.61720405 0.59936422 0.93322997]
 [0.21589732 0.75599446 0.99419787 0.83013019 0.32557365]
 [0.82958217 0.63433591 0.30494251 0.52897718 0.72091973]
 [0.07162021 0.33427732 0.36384985 0.03783377 0.4927138 ]
 [0.85683844 0.14624114 0.99847264 0.4454132  0.53520533]]

🔹 Array Name: 'array3'
[ 1.          6.44444444 11.88888889 17.33333333 22.77777778 28.22222222
 33.66666667 39.11111111 44.55555556 50.        ]

🎯 Accessing arrays using dynamic variables:
array1: [0 1 2 3 4 5 6 7 8 9]
array2: [[0.18251434 0.84915638 0.61720405 0.59936422 0.93322997]
 [0.21589732 0.75599446 0.99419787 0.83013019 0.32557365]
 [0.82958217 0.63433591 0.30494251 0.52897718 0.72091973]
 [0.07162021 0.33427732 0.36384985 0.03783377 0.4927138 ]
 [0.85683844 0.14624114 0.99847264 0.4454132  0.53520533]]
array3:

# Lambda Functions in Python

small anonymous function that can have multiple arguments but only a single expression.

variable =  lambda arguments : expression


When to Use Lambda Functions?

✅ When you need a short function for one-time use
✅ When using functions like map(), filter(), reduce()
✅ When sorting data with custom criteria


In [66]:
sum = lambda a,b : 5+6

print(sum(4,5))

11


map() function applies a function to all items in an iterable.

In [72]:
Num_list = [1,2,3,4]

Square_Each_Number = list(map(lambda x: x**2, Num_list ))

print(Square_Each_Number)

[1, 4, 9, 16]


filter() function filters elements based on a condition.

In [73]:
Num_list = [1,2,3,4]

Even_Numbers = list(filter(lambda x:x%2==0, Num_list))

print(Even_Numbers)

[2, 4]


In [78]:
Num_list = [1,2,3,4]

Even_Numbers = filter(lambda x:x%2==0, Num_list)

print(Even_Numbers)

print(list(Even_Numbers))

[2, 4]


# Reduce

In [77]:
## from functools import reduce

nums = [1, 2, 3, 4, 5]
product = reduce(lambda x, y: x * y, nums)
print(product)  # Output: 120

120


# Sorted

In [79]:
name_age = [("gt",43),("kk",28),("nn",51)]


age_sorted = sorted(name_age,  key = lambda x : x[1])

print(age_sorted)


[('kk', 28), ('gt', 43), ('nn', 51)]


# Conditional Expressions in Lambda

In [81]:
max_num = lambda x,y : x if x > y else y

max_num(40,55)

55

# Multiple Arguments in Lambda

In [83]:
mul = lambda x,y,z :  x*y*z

mul(2,3,4)

24

# Lambda in List Comprehensions

In [94]:
nums = [1, 2, 3, 4, 5]



def double(y):
    return y * 2

double_nums_1 = [double(y) for y in nums]
print(double_nums_1)



double_nums_2 = list(map(lambda x: x * 2, nums))
print(double_nums_2)



double_nums_3= [(lambda x: x * 2) (x) for x in nums]
print(double_nums_3)  # Output: [2, 4, 6, 8, 10]



double_nums_4 = [x * 2 for x in nums]
print(double_nums_4)

[2, 4, 6, 8, 10]
[2, 4, 6, 8, 10]
[2, 4, 6, 8, 10]
[2, 4, 6, 8, 10]


In [111]:
nums =  [1,2,3,4,5]
nums2 =  [1,2,2,3,4,4,5,6,6,6]


square_nums_list =  [x*x for x  in nums]
print(square_nums_list)

cube_nums_set =  {x*x*x for x  in nums2}
print(cube_nums_set)


even_nums_list = [x  for  x  in  nums if x % 2 == 0]
print(even_nums_list)


square_nums_dict =  {x : x*x for x  in nums}
print(square_nums_dict)


[1, 4, 9, 16, 25]
{64, 1, 8, 216, 27, 125}
[2, 4]
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [113]:
num = [1,2,2,3,4,4,4,5]

print(set(num))

print(list(set(num)))

{1, 2, 3, 4, 5}
[1, 2, 3, 4, 5]


# Generator Expressions (Memory Efficient Alternative to List Comprehensions)

In [116]:
squares = (x**2 for x in range(1, 100))  # Uses less memory than a list
print(next(squares))  # Output: 1
print(next(squares)) 
print(next(squares))
# Output: 4

1
4
9


In [117]:
power = lambda y : 10**y

print(power(2))





100


In [119]:
from functools import partial
def power(x, y):
    return x ** y


square = partial(power, 2)  # Locks `x=2`
print(square(3))

8


In [139]:
from functools import partial

def power(x, y):
    return x ** y

# Initialize values
x_value = 2  # Starting value of x
y_fixed = 3  # Keep y constant
iterations = 9  # Number of iterations

for i in range(1, iterations + 1):
    square = partial(power, x_value)  # Lock `x=x_value`
    print(f"Iteration {i}: {x_value}^{y_fixed} =", square(y_fixed))  # Keep y fixed

    # Every 3 iterations, increment x_value
    
    x_value += 1

Iteration 1: 2^3 = 8
Iteration 2: 3^3 = 27
Iteration 3: 4^3 = 64
Iteration 4: 5^3 = 125
Iteration 5: 6^3 = 216
Iteration 6: 7^3 = 343
Iteration 7: 8^3 = 512
Iteration 8: 9^3 = 729
Iteration 9: 10^3 = 1000


In [140]:
power = lambda x, y: x ** y

# Initialize values
x_value = 2  # Starting value of x
y_fixed = 3  # Keep y constant
iterations = 9  # Number of iterations

for i in range(1, iterations + 1):
    print(f"Iteration {i}: {x_value}^{y_fixed} =", power(x_value, y_fixed))  # Call lambda directly

    # Every 3 iterations, increment x_value
    x_value += 1

Iteration 1: 2^3 = 8
Iteration 2: 3^3 = 27
Iteration 3: 4^3 = 64
Iteration 4: 5^3 = 125
Iteration 5: 6^3 = 216
Iteration 6: 7^3 = 343
Iteration 7: 8^3 = 512
Iteration 8: 9^3 = 729
Iteration 9: 10^3 = 1000



# enumerate() (Indexing in Loops)


In [143]:
fruits = ["apple", "banana", "cherry"]
for index, fruit in enumerate(fruits, start=1):
    print(index, fruit)

1 apple
2 banana
3 cherry


# zip() (Combine Multiple Lists Easily)

In [147]:
names = ["Alice", "Bob", "Charlie"]
scores = [85, 92, 78]

combined = list(zip(names, scores))
print(combined) 

[('Alice', 85), ('Bob', 92), ('Charlie', 78)]


# itertools (Advanced Iteration Tricks)

In [149]:
from itertools import count

for num in count(10, 2):  # Start from 10, step by 2
    if num > 20:
        break
    print(num)


10
12
14
16
18
20


# Creating Combinations

In [152]:
from itertools import combinations

items = ["A", "B", "C"]
print(list(combinations(items, 2)))

[('A', 'B'), ('A', 'C'), ('B', 'C')]


In [157]:
students = [("Alice", 85), ("Bob", 78), ("Charlie", 92)]

from operator import itemgetter


sorted_students1 = sorted(students, key=lambda x: x[1])
sorted_students2 = sorted(students, key=itemgetter(1))

print(sorted_students1)
print(sorted_students2)

[('Bob', 78), ('Alice', 85), ('Charlie', 92)]
[('Bob', 78), ('Alice', 85), ('Charlie', 92)]


In [158]:
book = ("The Alchemist", 10540)


def some_name(x):
    return x[1]

price = some_name(book)
print("Extracted value:", price)      


some_name = lambda x: x[1]

price = some_name(book)
print("Extracted value:", price)

Extracted value: 10540
Extracted value: 10540


In [159]:
def get_price(book):
    return book[1]  # Extracts the second element (price)

books = [("Book1", 500), ("Book2", 200), ("Book3", 800)]
sorted_books = sorted(books, key=get_price)  # Sorts books based on price

print(sorted_books)

[('Book2', 200), ('Book1', 500), ('Book3', 800)]


In [ ]:
def get_price(book):
    return book[1]  # Extracts the second element (price)

def bubble_sort(books):
    n = len(books)
    for i in range(n):
        for j in range(0, n - i - 1):
            if get_price(books[j]) > get_price(books[j + 1]):  # Compare prices
                books[j], books[j + 1] = books[j + 1], books[j]  # Swap
    return books

# Sample books
books = [("A", 500), ("B", 200), ("C", 800)]
sorted_books = bubble_sort(books)  # Sort books

# Print sorted books
print(sorted_books)

In [160]:
def extract_price(book):
    return book[1]  # Extracts price from tuple

books = [("Book1", 500), ("Book2", 200), ("Book3", 800)]
prices = list(map(extract_price, books))  # Maps function to list

print(prices) 

[500, 200, 800]


## any() and all() (Quick Logical Checks on Lists)

In [162]:
nums = [1, 3, 5, 7, 8]
print(any(x % 2 == 0 for x in nums))  # Output: True

True


In [163]:
nums = [2, 4, 6, 8]
print(all(x % 2 == 0 for x in nums))  # Output: True

True


In [ ]:
%autosave 0